### ISSUE TITLE
Adding comments to Outline

### ISSUE THREAD

**Issue by ldm1417** [TheClams/SystemVerilog#12]
Hello,
I've figured out that SystemVerilog package works with Outline package and is able to add there labels of the **begin** and **fork** blocks of code.
Is it possible to add comments to the Outline? Let's say all the comments starting with //- (double slashes and single dash) or //-- (double slashes and double dashes)?
I tried to do this with the PackageResourceViewer package and BetterGoTo package, but things do not work perfectly. Probably I'm missing something ... Since you created the package and more familiar with it, probably you could cap the issue more... 
Could you please help with adding the tagged comments (//- and //--) to Outline?
Thank you a lot in advance!

**Comment by ldmas** [comment]
Please refer to [https://github.com/warmdev/SublimeOutline/issues/2#issuecomment-256441587 ](url)

**Comment by ldm1417** [comment]
Any response?
