### ISSUE TITLE
Provide manual way of installation without "Package Control"

### ISSUE THREAD

**Issue by Khaled-Ismail** [TheClams/SystemVerilog#18]
Can you please provide the ".sublime-package" as I can't install through "Package Control" since the company where I work imposes network restrictions?

I installed "Package Control" itself manually so I believe it's possible to install "SystemVerilog" package manually as well provided that the ".sublime-package" is available.

**Comment by TheClams** [comment]
Just clone the repo in your package directory.
The sublime-package file is just a zip of the repo
