### ISSUE TITLE
Support for tracing drivers across module boundaries

### ISSUE THREAD

**Issue by awall13** [TheClams/SystemVerilog#22]
It would be nice if GoTo Driver could trace across module boundaries. To help the user control it (and control the performance hit), one way to do it would be to trace one level at a time, and let the user trace repeatedly to cross additional module hierarchies. I don't have the code clean enough to be worthy of a pull request yet, but I've attached a modified version of verilog_navigation with the rough idea. 
[sv_trace_drivers.zip](https://github.com/TheClams/SystemVerilog/files/5382302/sv_trace_drivers.zip)

Thoughts? I can clean this up into a pull request if you'd like. Thanks!

**Comment by TheClams** [comment]
Thanks for the suggestion, it is a good feature to have indeed.
It is now implemented in the v2.24.0 and seems ok in the few test I did.
