### ISSUE TITLE
code gets deleted when i align or reindent 

### ISSUE THREAD

**Issue by shafqatu** [TheClams/SystemVerilog#23]
When import package and have parameterized module at the sometime then alignment and re-indent does not work, they destroy the code. 

I am also attaching the screenshots. Please note my import of package is a bit unorthodox, it is after the name of module and before the parameters which is a legal systemverilog syntax.

![Screenshot from 2020-10-27 02-11-04](https://user-images.githubusercontent.com/12128703/97244871-0b132900-17fa-11eb-9349-0e46d5f63e06.png)
![Screenshot from 2020-10-27 02-11-28](https://user-images.githubusercontent.com/12128703/97244875-0c445600-17fa-11eb-8734-8c9d2aa4a614.png)
![Screenshot from 2020-10-27 02-11-59](https://user-images.githubusercontent.com/12128703/97244877-0cdcec80-17fa-11eb-8366-ccd5cb614e11.png)

**Comment by TheClams** [comment]
You are missing a comma after the rst_n which might explain the problem.
And next time please provide raw text instead of screenshot it makes
my life easier when i have to reproduce the problem.

**Comment by shafqatu** [comment]
`module test_sram
	import test_pkg::*;
#(
	parameter LENGTH      = 8192,
	parameter IS_IMEM     = 1   , // this is just for simulation to lead hex files
	parameter MEM_TYPE    = 0   , // 0 = single cycle pipeline, 1 = multi cycle
	parameter NUM_OS_RW   = 8   , // number of outstanding read and writes, beofe things get blocked
	parameter ALMOST_FULL = 2   , // this define how long before busy signals is set high
	// this is can set depending on pipes between blocks, should be less than NUM_OS_RW
) (
	input                clk    , // Clock
	input                rst_n  , // Asynchronous reset active low
	input  abee_master_t ib_sram,
	output abee_slave_t  ob_sram
);


endmodule`

**Comment by shafqatu** [comment]
module test_sram
	import test_pkg::*;
#(
	parameter LENGTH      = 8192,
	parameter IS_IMEM     = 1   , // this is just for simulation to lead hex files
	parameter MEM_TYPE    = 0   , // 0 = single cycle pipeline, 1 = multi cycle
	parameter NUM_OS_RW   = 8   , // number of outstanding read and writes, beofe things get blocked
	parameter ALMOST_FULL = 2   , // this define how long before busy signals is set high
	// this is can set depending on pipes between blocks, should be less than NUM_OS_RW
) (
	input                clk    , // Clock
	input                rst_n  , // Asynchronous reset active low
	input  abee_master_t ib_sram,
	output abee_slave_t  ob_sram
);


endmodule

**Comment by shafqatu** [comment]
`module test_sram
	import test_pkg::*;
#(
	parameter LENGTH      = 8192,
	parameter IS_IMEM     = 1   ,
	parameter MEM_TYPE    = 0   ,
	parameter NUM_OS_RW   = 8   ,
	parameter ALMOST_FULL = 2
) (
	input                clk    , // Clock
	input                rst_n  , // Asynchronous reset active low
	input  abee_master_t ib_sram,
	output abee_slave_t  ob_sram
);


endmodule`

**Comment by shafqatu** [comment]
module test_sram
	import test_pkg::*;
#(
	parameter LENGTH      = 8192,
	parameter IS_IMEM     = 1   ,
	parameter MEM_TYPE    = 0   ,
	parameter NUM_OS_RW   = 8   ,
	parameter ALMOST_FULL = 2
) (
	input                clk    , // Clock
	input                rst_n  , // Asynchronous reset active low
	input  abee_master_t ib_sram,
	output abee_slave_t  ob_sram
);


endmodule

**Comment by shafqatu** [comment]
I hope this helps

**Comment by TheClams** [comment]
It works fine for me:
![align_module](https://user-images.githubusercontent.com/5270125/97529234-c29d6c00-19af-11eb-915f-218bab93850f.gif)

**Comment by TheClams** [comment]
Finally managed to re-create the issue : it happens only if you run the alignement outside of the parameter/port list ...
Anyway this is now fixed in 3.0.6
