### ISSUE TITLE
ST4 Support

### ISSUE THREAD

**Issue by roowatt** [TheClams/SystemVerilog#31]
ST4 is currently not supported and I had to disable package.

What are the plans to support Sublime Text 4?

**Comment by TheClams** [comment]
Not sure why you think it is not supported ? it has been for more than a year now,  the highlight and completion were updated for ST4: maybe try reinstalling the package.

**Comment by roowatt** [comment]
Sorry for the noise, I got a message about not being supported but it must have been a corner case in the upgrade process.

Again, sorry for the noise.
