### ISSUE TITLE
Is Github or BitBucket the 'golden source'

### ISSUE THREAD

**Issue by markusdd** [TheClams/SystemVerilog#4]
Hi,

I've been using this extension for a long time now and like it very much.
I do maintain a private copy to match seom different coding styles which are incompatible with the official version.

So I was wondering: Is this the up-to-date version here on Github or is it still maintained on Bitbucket like in the past?

I still run off of Bitbucket, if this is the new place to look I would migrate to git, which I prefer anyway.

**Comment by TheClams** [comment]
Bitbucket is not maintained anymore since they are dropping support for mercurial. 
This is repo is the official one.

**Comment by markusdd** [comment]
Thanks for the quick response!
