### ISSUE TITLE
Navigate to  subfield definition in sv

### ISSUE THREAD

**Issue by erihsu** [TheClams/SystemVerilog#40]
Suppose a case that I have class A and class B
```systemverilog
class A;
   int d1;
   int d2;
  ....
endclass

class B extends A;
   A.d1 = 2;
endclass
```
where B extends A, and I want to navigate to d1 declaration location from class B

**Comment by TheClams** [comment]
In 3.1.0 you can now use the goto_declaration command to navigate to the declaration of class/struct/interface members

**Comment by erihsu** [comment]
@TheClams Thanks for your work
