### ISSUE TITLE
Disable end parenthesis alignment?

### ISSUE THREAD

**Issue by perchrc** [TheClams/SystemVerilog#41]
The alignment feature will currently align module instantiations like this:

```
my_module #(
    .ABCD(100  ),
    .EF  (1    ),
    .G   (10000)
) i_my_module (
    .clk    (clk                 ),
    .resetn (resetn              ),
    .i_valid(my_input_port_valid ),
    .i_data (my_input_port       ),
    .o_valid(my_output_port_valid),
    .o_data (my_output_port      )
);
```

This looks good to me, but the problem is that other people I am working with who do not use Sublime Text will have to maintain this alignment manually (or create a misalignment mess) when they do something like renaming a signal. Could you please consider adding a mode to disable end-parenthesis alignment to mitigate this problem, so that the aligned code will look like the following instead?

```
my_module #(
    .ABCD(100),
    .EF  (1),
    .G   (10000)
) i_my_module (
    .clk    (clk),
    .resetn (resetn),
    .i_valid(my_input_port_valid),
    .i_data (my_input_port),
    .o_valid(my_output_port_valid),
    .o_data (my_output_port)
);
```
This would make the code much easier to maintain for non-ST users, and I believe it matches the alignment behavior of other editors better. I have turned off `sv.align_comma_semicolon` but it doesn't seem to affect this.

**Comment by TheClams** [comment]
In 3.1.0 there is now the setting `sv.align_paren` that you can set to false to get the result you want.
The old setting `sv.param_port_alignment` gives a slightly different result where even the opening parenthesis is not aligned.
