### ISSUE TITLE
 keyword highlighting issue

### ISSUE THREAD

**Issue by erihsu** [TheClams/SystemVerilog#42]
```dist``` keyword not highlighted

**Comment by TheClams** [comment]
It is : ![dist](https://user-images.githubusercontent.com/5270125/144701447-5b2d76dd-a997-4180-af34-9a55ebd9f458.png)

Please provide an example where this would not be the case.

**Comment by erihsu** [comment]
Hi,
Sorry for late replay. Yes, ```dist``` can be highlighted in constraint block. But in standalone mode it's disabled. Maybe it's not a issue  if ```dist``` only used in constraint.

**Comment by TheClams** [comment]
After checking the specification it can actually be used outside of a constraint (typically an iff statement), so I updated the syntax.
Thanks for the report.
