### ISSUE TITLE
packed array bracket shows false syntax error

### ISSUE THREAD

**Issue by Ali-Flt** [TheClams/SystemVerilog#44]
I provide an example:

![image](https://user-images.githubusercontent.com/60854595/147662070-e9137cc0-3e19-4227-b189-02e4d720c31a.png)

There is nothing wrong with this line of code, it also compiles and runs without error. Please fix this cause it's not convenient to see false syntax errors in code. 
Thanks

**Comment by TheClams** [comment]
Fixed in 3.1.3
