### ISSUE TITLE
Instance Name indication in the Port Declaration

### ISSUE THREAD

**Issue by ldm1417** [TheClams/SystemVerilog#46]
Hi All,

I'm working with the modules, which have a long list of the ports. So, without scrolling the Editor window up (to the line where the module is instantioned), it's hard to understand what module/instance the observed port belongs to. 

Is it possible to add a tooltip, which would show the instance name the pointed/selected port belongs to? 

So, as for me, I see at least two solutions to the problem:
1) adding a tooltip to the port name, which would indicate what module name the current port belongs to
2) Syncing the Editor to Outline Panel (syncing in the opposite direction (Output Panel to Editor) it's already exists). So, clicking on the port will highlight the instance name in the Outline Panel

But honestly I don't know how to implement the above solutions... Does anybody know? Are there another solutions to this problem? 

As for me this feature is critical because I'm working with the instances, which usually have a very long list of the ports.

Thank you in advance!

**Comment by TheClams** [comment]
There is already an option for that: Preferences->package settings->SystemVerilog->Settings
It should open a window with two settings: the reference on the left and your settings on the right: just add the line 
`"sv.tooltip_show_module_on_port": true` on the right.
