### ISSUE TITLE
Could you fix this, please?

### ISSUE THREAD

**Issue by Bitmanyga** [TheClams/SystemVerilog#53]
![image](https://user-images.githubusercontent.com/59740338/176955821-7a714c5e-3959-40af-a798-f28f6905bd0a.png)

I dont know how to fix these appearing variants with letters

**Comment by TheClams** [comment]
I doubt this has anything to do with this plugin: completion I provide usually have indicator of type, and some hint, here there is nothing.
Either you have some other plugin doing this or just some issue with ST basic completion: try disabling plugin to check where this is coming from and check the completion option of ST.
