### ISSUE TITLE
label for autocompletion

### ISSUE THREAD

**Issue by xinpan1992** [TheClams/SystemVerilog#59]
Hi,

I found out the for always_ff and other keywords, the label only applies for beginning of the code.
Is there anyway to also add the label at the end of the auto-compelted code.

Below if what the current setting looks like.
```
always_ff @(posedge clk or negedge rstb) begin : proc_  // label for only begin
    if(~rstb) begin
         <= 0;
    end else begin
         <= ;
    end
end
```

This is what I was trying to get.
```
always_ff @(posedge clk or negedge rstb) begin : proc_  // label for begin
    if(~rstb) begin
         <= 0;
    end else begin
         <= ;
    end
end : proc_ // label for begin
```

**Comment by TheClams** [comment]
Should be available in latest version (3.1.11) : you just need to set the setting sv.always_end_label to true
