### ISSUE TITLE
hovering mouse over class name in a file doesn't give the preview

### ISSUE THREAD

**Issue by naveen2393** [TheClams/SystemVerilog#61]
from past few days I'm facing issue in linux where I'm not getting the definition of the classes when I hover mouse over the name despite opening folder to project. the same is working in windows, tried re-installing everything and still the same. 
I got a warning something related to metadata for the package. Is anyone else facing similar issue?
I'm using build 3211.

**Comment by TheClams** [comment]
Have you tried restarting Sublime ?
