### ISSUE TITLE
Alignment support blank/comment lines in the signals declaration area?

### ISSUE THREAD

**Issue by ch3ch2sh** [TheClams/SystemVerilog#63]
Alignment support blank/comment lines in the signals declaration area?
like:
wire   [127:0]  a;

reg    [    7:0]  b;
//comments
reg    [    1:0]  c;

**Comment by TheClams** [comment]
I added a new option (sv.align_group_decl) in latest version that you can set to true so that alignment behaves like you want.

**Comment by ch3ch2sh** [comment]
Thank you very much.
