### ISSUE TITLE
module syntax error

### ISSUE THREAD

**Issue by godenfreemans** [TheClams/SystemVerilog#68]
something wrong:
"1ns" or "1 ns" has different result.
![image](https://github.com/TheClams/SystemVerilog/assets/11087671/08b5baea-b450-4ed6-8f51-899e02ae47ed)

![image](https://github.com/TheClams/SystemVerilog/assets/11087671/41f2a173-f81e-432a-88ea-aea00088486a)

**Comment by godenfreemans** [comment]
im ensure it's okey in 3.2.2.

**Comment by TheClams** [comment]
Fixed in 3.3.1

**Comment by godenfreemans** [comment]
thanks for your fix.😊
