### ISSUE TITLE
Latest package causes cursor lag

### ISSUE THREAD

**Issue by cmdennett** [TheClams/SystemVerilog#69]
This is going to be a bit difficult to describe, but starting yesterday I started experiencing strange cursor lag with Sublime Text 4 (4152) using the SystemVerilog package.  The problem more specifically is that in certain parts of the file if I hold down the arrow keys the cursor may move one spot and then doesn't move.  If I let go of the arrow key the cursor will then jump to an appropriate spot as if it had been moving (though slowly).  Same goes for page-up/down and the like.  This clearly makes code highlighting painful.  Using the mouse is better, but you can see it lagging and struggling.  If there's something active on the sublime window (like a spinny icon on loading a directory), it hangs when I'm trying to move the cursor.

I don't see the problem on other file types, like C++, TCL, or python.  I downgraded Sublime Text to rev 4107 but the problem persists.    The packagecontrol.io site mentions SystemVerilog was modified a day ago.  I'm not sure how to find any release notes or even how to get an older version.  I've made very few configuration changes to the defaults, so doubt there's something esoteric I'm doing.

**Comment by TheClams** [comment]
I did not notice the issue on my home PC but on a slower computer it was noticable: I pushed a fix for that (it might take a few hour for PackageControl to see that there is a new version).

If it still create issue you can try to set the settings sv.status to False : 
 - Menu preferences->Package settings -> SystemVerilog -> Settings
 - add line "sv.status" : false
