### ISSUE TITLE
apply color to ifdef expressions

### ISSUE THREAD

**Issue by jotego** [TheClams/SystemVerilog#71]
I, for one, use a lot of `ifdef` statements to conditionally parse code in common files. So the `ifdef` expressions are quite common in some files:

![imagen](https://github.com/TheClams/SystemVerilog/assets/1863036/328f99c8-fc43-465b-a7cd-e4bf232d3fac)

Having the preprocessor words, those marked with a ` tick, highlighted would make the code more readable. This should apply to predefined preprocessor keywords but also to the macros you refer to with the ` tick.

Thank you

**Comment by TheClams** [comment]
This looks like an issue with the definition of your color scheme:
![ifdef_highlight](https://github.com/TheClams/SystemVerilog/assets/5270125/0a7e0baf-dacb-459c-b7a6-da7683129739)


You need to have colors associated to `constant.other.preprocessor` for the ifdef and `support.variable` for the variables.
You can check the doc on how to do tune your color scheme: https://www.sublimetext.com/docs/color_schemes.html
