### ISSUE TITLE
Code alignment feature can lead to code breaks in certain scenarios

### ISSUE THREAD

**Issue by rayqqqm** [TheClams/SystemVerilog#73]
When align  module instantiations, comments don't seem to be handled correctly and will lead to code breaks.
for example:

before alignment

    sub_mod1 #(.PARA1(PARA1)) inst1    //this comment will lead to error
    (
        .io1(sm1),
        .io2(sm2),
        .io3(sm3)
    );

    sub_mod1 #(.PARA2(PARA2)) inst2    
    (
        .io1(sm1),
        .io2(sm2),
        .io3(sm3)
        //this comment will lead to error
    );

after alignment

    sub_mod1 #(.PARA1(PARA1)) inst1    //this comment will lead to error
        (
            .io1(sm1),
            .io2(sm2),
            .io3(sm3)

    sub_mod1 #(.PARA2(PARA2)) inst2 (
        .io1(sm1),
        .io2(sm2),
        .io3(sm3),
        //this comment will lead to error
    );

you can see the 1st  instantiation miss ')' and ';' and an extra comma is created on the last line of the 2nd instantiation.

**Comment by TheClams** [comment]
Fixed in 3.3.4
