### ISSUE TITLE
Unable to recognize brackets

### ISSUE THREAD

**Issue by WZ-Tong** [TheClams/SystemVerilog#74]
submodule: input [(parameter*2)-1:0] name;
instantize with: wire [(parameter*2)-1:0] name;

Output:
// TODO: Check connection ! Signal/port not matching : Expecting logic [parameter*2-1:0]  -- Found logic [(parameter*2)-1:0] 

Seems the parser? ignored the brackets.

**Comment by TheClams** [comment]
Fixed in 3.3.4
