### ISSUE TITLE
Hightlight mismatch when assign reg with delay

### ISSUE THREAD

**Issue by WZ-Tong** [TheClams/SystemVerilog#75]
![image](https://github.com/user-attachments/assets/23824ec4-4c36-4e49-a14a-e71f86fcefd7)
Blue:
![image](https://github.com/user-attachments/assets/d4f786da-d00c-4c83-88dd-b9ed16d371b9)
Yellow:
![image](https://github.com/user-attachments/assets/1c061004-e87b-47b2-9a56-2647751dbec7)

**Comment by TheClams** [comment]
Fixed in 3.3.5
